-- agenda (RF10 e RF11)
-- o prescritor cadastra os periodos da semana em q atende e quanto tempo dura cada consulta
-- o paciente pede um dos horarios livres e o prescritor confirma ou recusa

create table prescriber_availability (
    id bigint generated by default as identity,
    prescriber_id bigint not null,
    day_of_week integer not null,
    start_time time not null,
    end_time time not null,
    primary key (id),
    constraint ck_prescriber_availability_day check (day_of_week between 1 and 7),
    constraint ck_prescriber_availability_period check (start_time < end_time),
    constraint fk_prescriber_availability_prescriber foreign key (prescriber_id) references prescriber (id)
);

create index idx_prescriber_availability_prescriber on prescriber_availability (prescriber_id, day_of_week);

alter table prescriber add column appointment_duration_minutes integer default 60 not null;
alter table prescriber add constraint ck_prescriber_appointment_duration
    check (appointment_duration_minutes between 15 and 240);

-- o motivo q o paciente escreve ao pedir o horario fica longe dos campos clinicos
alter table appointment add column patient_note TEXT;

-- o pedido do paciente espera a resposta como SOLICITADA e o recusado vira RECUSADA
-- a regra antiga do status n tinha nome entao a coluna eh recriada com uma regra nomeada
alter table appointment add column appointment_status varchar(20);
update appointment set appointment_status = coalesce(status, 'AGENDADA');
alter table appointment drop column status;
alter table appointment rename column appointment_status to status;
alter table appointment alter column status set not null;
alter table appointment add constraint ck_appointment_status
    check (status in ('SOLICITADA', 'AGENDADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', 'RECUSADA'));
