-- escalas (RF08, RF09, RF21 a RF26 e RF32)
-- antes cada escala tinha tabela servico e tela propria, e o formulario vivia espalhado
-- agora a resposta de qualquer escala cai numa tabela so, com o escore e a faixa junto
-- o formulario de cada escala fica descrito no codigo, entao escala nova n pede coluna nova

create table scale_task (
    id bigint generated by default as identity,
    patient_id bigint not null,
    prescriber_id bigint not null,
    scale_type varchar(40) not null,
    period_start date not null,
    period_end date not null,
    status varchar(20) not null,
    answered_at date,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint ck_scale_task_status check (status in ('PENDENTE', 'RESPONDIDA', 'NAO_RESPONDIDA')),
    constraint ck_scale_task_type check (scale_type in ('ACOMPANHAMENTO_SEMANAL', 'REGISTRO_SONO',
        'ESCALA_HAMILTON', 'ESCALA_PITTSBURGH', 'REGISTRO_DOR', 'REGISTRO_TEA', 'ANAMNESE')),
    constraint ck_scale_task_period check (period_end >= period_start),
    constraint fk_scale_task_patient foreign key (patient_id) references patient (id),
    constraint fk_scale_task_prescriber foreign key (prescriber_id) references prescriber (id)
);

create index idx_scale_task_patient on scale_task (patient_id, status);
create index idx_scale_task_prescriber on scale_task (prescriber_id, status);

create table scale_response (
    id bigint generated by default as identity,
    patient_id bigint not null,
    prescriber_id bigint,
    appointment_id bigint,
    task_id bigint,
    scale_type varchar(40) not null,
    period_start date not null,
    period_end date not null,
    answers TEXT not null,
    score integer,
    score_band varchar(120),
    reviewed_at timestamp(6),
    reviewed_by_id bigint,
    annulled_at timestamp(6),
    annulled_by_id bigint,
    annulment_reason TEXT,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint ck_scale_response_type check (scale_type in ('ACOMPANHAMENTO_SEMANAL', 'REGISTRO_SONO',
        'ESCALA_HAMILTON', 'ESCALA_PITTSBURGH', 'REGISTRO_DOR', 'REGISTRO_TEA', 'MINI_EXAME_ESTADO_MENTAL')),
    constraint ck_scale_response_period check (period_end >= period_start),
    constraint fk_scale_response_patient foreign key (patient_id) references patient (id),
    constraint fk_scale_response_prescriber foreign key (prescriber_id) references prescriber (id),
    constraint fk_scale_response_appointment foreign key (appointment_id) references appointment (id),
    constraint fk_scale_response_task foreign key (task_id) references scale_task (id),
    constraint fk_scale_response_reviewed_by foreign key (reviewed_by_id) references users (id),
    constraint fk_scale_response_annulled_by foreign key (annulled_by_id) references users (id)
);

create index idx_scale_response_patient on scale_response (patient_id, scale_type, period_start);
create index idx_scale_response_task on scale_response (task_id);

-- a programacao de horarios do diario do sono, q o prescritor define no acompanhamento (RF22)
alter table treatment_protocol add column sleep_bed_time time;
alter table treatment_protocol add column sleep_wake_time time;

-- as tabelas antigas saem, uma por escala. o sistema nunca foi implantado, entao n ha dado pra migrar
drop table mental_state_exam;
drop table follow_up;
drop table hamilton_scale;
drop table pittsburgh_scale;
drop table pain_log;
drop table sleep_log;
drop table tealog;
drop table assigned_scale;
