-- esquema base do 2ag
-- junta as antigas migracoes 1 a 8 numa so ja com as correcoes de integridade
-- nome email e senha obrigatorios e indice em toda chave estrangeira
-- conta com flag de ativa e controle de tentativas erradas de login
-- tabela de administrador pra conta q provisiona prescritor
-- daqui pra frente toda mudanca de esquema eh uma migracao nova

-- ---------------------------------------------------------------
-- usuarios
-- ---------------------------------------------------------------

create table users (
    id bigint generated by default as identity,
    name varchar(255) not null,
    cpf varchar(255) unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    birth_date date,
    phone varchar(255),
    street varchar(255),
    number varchar(255),
    city varchar(255),
    state varchar(255),
    country varchar(255),
    active boolean not null default true,
    failed_login_attempts integer not null default 0,
    locked_until timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table admin (
    id bigint not null,
    primary key (id),
    constraint fk_admin_users foreign key (id) references users (id)
);

create table prescriber (
    id bigint not null,
    profession varchar(255),
    professional_code varchar(255) unique,
    registry_type varchar(255),
    registry_number varchar(255),
    primary key (id),
    unique (registry_type, registry_number),
    constraint fk_prescriber_users foreign key (id) references users (id)
);

create table patient (
    id bigint not null,
    prescriber_id bigint,
    primary key (id),
    constraint fk_patient_users foreign key (id) references users (id),
    constraint fk_patient_prescriber foreign key (prescriber_id) references prescriber (id)
);

create index idx_patient_prescriber on patient (prescriber_id);

-- ---------------------------------------------------------------
-- consulta e prescricao
-- ---------------------------------------------------------------

create table appointment (
    id bigint generated by default as identity,
    patient_id bigint not null,
    prescriber_id bigint not null,
    date_time timestamp(6) not null,
    duration_minutes integer not null default 60,
    modality varchar(255) check (modality in ('PRESENCIAL', 'REMOTA')),
    status varchar(255) check (status in ('AGENDADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA')),
    diagnosis TEXT,
    clinical_observation TEXT,
    therapeutic_plan TEXT,
    evolution TEXT,
    physical_exam TEXT,
    complementary_exams TEXT,
    blood_pressure varchar(255),
    weight float4,
    height integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_appointment_patient foreign key (patient_id) references patient (id),
    constraint fk_appointment_prescriber foreign key (prescriber_id) references prescriber (id)
);

create index idx_appointment_patient on appointment (patient_id, date_time);
create index idx_appointment_prescriber on appointment (prescriber_id, date_time);

create table prescription (
    id bigint generated by default as identity,
    appointment_id bigint not null,
    product_description TEXT,
    posology TEXT,
    brand varchar(255),
    concentration varchar(255),
    spectrum varchar(255),
    observation TEXT,
    volume varchar(255),
    administration_route varchar(255),
    instructions TEXT,
    precautions TEXT,
    expected_effects TEXT,
    treatment_duration_days integer,
    next_consultation_date date,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_prescription_appointment foreign key (appointment_id) references appointment (id)
);

create index idx_prescription_appointment on prescription (appointment_id);

create table dose_escalation_step (
    id bigint generated by default as identity,
    prescription_id bigint not null,
    week integer,
    dosage varchar(255),
    note TEXT,
    primary key (id),
    constraint fk_dose_step_prescription foreign key (prescription_id) references prescription (id)
);

create index idx_dose_step_prescription on dose_escalation_step (prescription_id);

create table mental_state_exam (
    id bigint generated by default as identity,
    appointment_id bigint not null,
    temporal_orientation integer,
    spatial_orientation integer,
    registration integer,
    attention_and_calculation integer,
    recall integer,
    naming integer,
    repetition integer,
    command integer,
    reading integer,
    writing integer,
    copying integer,
    score integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_meem_appointment foreign key (appointment_id) references appointment (id)
);

create index idx_meem_appointment on mental_state_exam (appointment_id);

-- ---------------------------------------------------------------
-- escalas preenchidas pelo paciente
-- ---------------------------------------------------------------

create table anamnesis (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    reason_for_visit TEXT,
    profession varchar(255),
    diet TEXT,
    anxiety TEXT,
    observation TEXT,
    pain TEXT,
    adverse_reaction TEXT,
    previous_diagnosis TEXT,
    smoking_habits TEXT,
    expectations TEXT,
    current_medication TEXT,
    treatment_awareness TEXT,
    genetic_condition TEXT,
    previous_treatment TEXT,
    family_history TEXT,
    height varchar(255),
    weight varchar(255),
    alcohol_consumption TEXT,
    sleep_habits TEXT,
    substance_use TEXT,
    physical_activity TEXT,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_anamnesis_patient foreign key (patient_id) references patient (id)
);

create index idx_anamnesis_patient on anamnesis (patient_id, assessment_date);

create table follow_up (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    morning_drops integer,
    afternoon_drops integer,
    comment TEXT,
    tremor integer,
    rigidity_spasticity integer,
    nausea integer,
    concentration integer,
    appetite integer,
    social_interaction integer,
    disposition integer,
    intestinal_function integer,
    anxiety integer,
    substance_reduction integer,
    pain integer,
    sports_performance integer,
    sleep integer,
    dermatological_disease integer,
    mood integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_follow_up_patient foreign key (patient_id) references patient (id)
);

create index idx_follow_up_patient on follow_up (patient_id, assessment_date);

create table hamilton_scale (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    anxious_mood integer,
    tension integer,
    fears integer,
    insomnia integer,
    cognition integer,
    depressed_mood integer,
    somatic_motor integer,
    somatic_sensory integer,
    cardiovascular_symptoms integer,
    respiratory_symptoms integer,
    gastrointestinal_symptoms integer,
    genitourinary_symptoms integer,
    autonomic_symptoms integer,
    interview_behavior integer,
    ham_score integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_hamilton_patient foreign key (patient_id) references patient (id)
);

create index idx_hamilton_patient on hamilton_scale (patient_id, assessment_date);

create table pain_log (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    pain_intensity integer,
    basic_activity_interference integer,
    social_activity_interference integer,
    sleep_interference integer,
    productivity_interference integer,
    extra_medication integer,
    observation TEXT,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_pain_log_patient foreign key (patient_id) references patient (id)
);

create index idx_pain_log_patient on pain_log (patient_id, assessment_date);

create table pittsburgh_scale (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    usual_bed_time time(6),
    minutes_to_fall_asleep integer,
    usual_wake_up_time time(6),
    actual_sleep_hours float4,
    freq_cannot_fall_asleep integer,
    freq_wakes_up_middle_night integer,
    freq_wake_up_for_bathroom integer,
    freq_cannot_breathe integer,
    freq_cough_or_snore integer,
    freq_feel_cold integer,
    freq_feel_hot integer,
    freq_have_bad_dreams integer,
    freq_have_pain integer,
    other_reason_to_trouble_sleep TEXT,
    freq_other_reason integer,
    sleep_quality_rating integer,
    freq_use_sleep_medication integer,
    freq_trouble_staying_awake integer,
    trouble_with_enthusiasm integer,
    room_partner integer,
    psqi_score integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_pittsburgh_patient foreign key (patient_id) references patient (id)
);

create index idx_pittsburgh_patient on pittsburgh_scale (patient_id, assessment_date);

create table sleep_log (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    bed_time time(6),
    wake_up_time time(6),
    time_in_bed float4,
    time_to_fall_asleep integer,
    times_woken_up integer,
    total_time_awake integer,
    total_sleep_time float4,
    total_awake_sleep float4,
    is_common_day boolean,
    fatigue integer,
    stress integer,
    daytime_sleepiness integer,
    inattention integer,
    irritability integer,
    pain integer,
    health_perception integer,
    physical_activity_time float4,
    time_away_from_home float4,
    used_sleep_medication boolean,
    alcohol_consumption integer,
    naps_time integer,
    coffee_consumption integer,
    nighttime_smoking integer,
    total_time_awake_during_night integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_sleep_log_patient foreign key (patient_id) references patient (id)
);

create index idx_sleep_log_patient on sleep_log (patient_id, assessment_date);

create table tealog (
    id bigint generated by default as identity,
    patient_id bigint not null,
    assessment_date date not null,
    quality_of_life integer,
    freq_aggressiveness integer,
    freq_agitation integer,
    freq_sleep_issues integer,
    freq_social_interaction integer,
    freq_stereotypy integer,
    freq_appetite_issues integer,
    observation TEXT,
    tea_score integer,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_tealog_patient foreign key (patient_id) references patient (id)
);

create index idx_tealog_patient on tealog (patient_id, assessment_date);

-- ---------------------------------------------------------------
-- tarefas de escala e acompanhamento automatico
-- ---------------------------------------------------------------

create table assigned_scale (
    id bigint generated by default as identity,
    patient_id bigint not null,
    prescriber_id bigint not null,
    scale_type varchar(255) not null check (scale_type in ('ESCALA_HAMILTON', 'ESCALA_PITTSBURGH',
        'MINI_EXAME_ESTADO_MENTAL', 'REGISTRO_DOR', 'REGISTRO_SONO', 'REGISTRO_TEA', 'ANAMNESE',
        'ACOMPANHAMENTO_SEMANAL')),
    status varchar(255) not null check (status in ('PENDENTE', 'CONCLUIDO')),
    assigned_date date not null,
    completed_date date,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_assigned_scale_patient foreign key (patient_id) references patient (id),
    constraint fk_assigned_scale_prescriber foreign key (prescriber_id) references prescriber (id)
);

create index idx_assigned_scale_patient on assigned_scale (patient_id, status);
create index idx_assigned_scale_prescriber on assigned_scale (prescriber_id, status);

create table treatment_protocol (
    id bigint generated by default as identity,
    patient_id bigint not null,
    prescriber_id bigint not null,
    start_date date not null,
    end_date date not null,
    active boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_protocol_patient foreign key (patient_id) references patient (id),
    constraint fk_protocol_prescriber foreign key (prescriber_id) references prescriber (id)
);

create index idx_protocol_patient on treatment_protocol (patient_id, active);

create table protocol_item (
    id bigint generated by default as identity,
    protocol_id bigint not null,
    scale_type varchar(255) not null check (scale_type in ('ESCALA_HAMILTON', 'ESCALA_PITTSBURGH',
        'MINI_EXAME_ESTADO_MENTAL', 'REGISTRO_DOR', 'REGISTRO_SONO', 'REGISTRO_TEA', 'ANAMNESE',
        'ACOMPANHAMENTO_SEMANAL')),
    periodicity varchar(255) not null check (periodicity in ('SEMANAL', 'QUINZENAL', 'MENSAL')),
    primary key (id),
    constraint fk_protocol_item_protocol foreign key (protocol_id) references treatment_protocol (id)
);

create index idx_protocol_item_protocol on protocol_item (protocol_id);

-- ---------------------------------------------------------------
-- notificacoes
-- ---------------------------------------------------------------

create table notification (
    id bigint generated by default as identity,
    user_id bigint not null,
    title varchar(255) not null,
    message TEXT not null,
    is_read boolean not null,
    type varchar(255) not null,
    link varchar(255),
    created_at timestamp(6) not null,
    primary key (id),
    constraint fk_notification_users foreign key (user_id) references users (id)
);

create index idx_notification_user on notification (user_id, created_at);
