-- esquema inicial do 2ag
--
-- gerado a partir das entidades jpa, ja com as correcoes de
-- integridade: campos de texto clinico em TEXT, cpf unico, e as
-- colunas created_at e updated_at em toda entidade clinica.
--
-- a partir daqui o esquema so muda por migracao nova. nunca edite
-- este arquivo depois que ele rodar em algum banco: o flyway guarda
-- o checksum e vai recusar a subida.


    create table anamnesis (
        assessment_date date not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        adverse_reaction TEXT,
        alcohol_consumption TEXT,
        anxiety TEXT,
        current_medication TEXT,
        diet TEXT,
        expectations TEXT,
        family_history TEXT,
        genetic_condition TEXT,
        height varchar(255),
        observation TEXT,
        pain TEXT,
        physical_activity TEXT,
        previous_diagnosis TEXT,
        previous_treatment TEXT,
        profession varchar(255),
        reason_for_visit TEXT,
        sleep_habits TEXT,
        smoking_habits TEXT,
        substance_use TEXT,
        treatment_awareness TEXT,
        weight varchar(255),
        primary key (id)
    );

    create table appointment (
        created_at timestamp(6) not null,
        date_time timestamp(6),
        id bigint generated by default as identity,
        patient_id bigint not null,
        prescriber_id bigint not null,
        updated_at timestamp(6) not null,
        clinical_observation TEXT,
        diagnosis TEXT,
        evolution TEXT,
        modality varchar(255) check (modality in ('PRESENCIAL','REMOTA')),
        status varchar(255) check (status in ('AGENDADA','EM_ANDAMENTO','CONCLUIDA','CANCELADA')),
        therapeutic_plan TEXT,
        primary key (id)
    );

    create table assigned_scale (
        assigned_date date,
        completed_date date,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        prescriber_id bigint not null,
        updated_at timestamp(6) not null,
        scale_type varchar(255) not null check (scale_type in ('ESCALA_HAMILTON','ESCALA_PITTSBURGH','MINI_EXAME_ESTADO_MENTAL','REGISTRO_DOR','REGISTRO_SONO','REGISTRO_TEA','ANAMNESE','ACOMPANHAMENTO_SEMANAL')),
        status varchar(255) not null check (status in ('PENDENTE','CONCLUIDO')),
        primary key (id)
    );

    create table follow_up (
        afternoon_drops integer,
        anxiety integer,
        appetite integer,
        assessment_date date not null,
        concentration integer,
        dermatological_disease integer,
        disposition integer,
        intestinal_function integer,
        mood integer,
        morning_drops integer,
        nausea integer,
        pain integer,
        rigidity_spasticity integer,
        sleep integer,
        social_interaction integer,
        sports_performance integer,
        substance_reduction integer,
        tremor integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        comment TEXT,
        primary key (id)
    );

    create table hamilton_scale (
        anxious_mood integer,
        assessment_date date not null,
        autonomic_symptoms integer,
        cardiovascular_symptoms integer,
        cognition integer,
        depressed_mood integer,
        fears integer,
        gastrointestinal_symptoms integer,
        genitourinary_symptoms integer,
        ham_score integer,
        insomnia integer,
        respiratory_symptoms integer,
        somatic_motor integer,
        somatic_sensory integer,
        tension integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table mental_state_exam (
        attention_and_calculation integer,
        command integer,
        naming integer,
        recall integer,
        registration integer,
        repetition integer,
        score integer,
        spatial_orientation integer,
        temporal_orientation integer,
        appointment_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table notification (
        is_read boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        link varchar(255),
        message TEXT not null,
        title varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    create table pain_log (
        assessment_date date not null,
        basic_activity_interference integer,
        extra_medication integer,
        productivity_interference integer,
        sleep_interference integer,
        social_activity_interference integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        observation TEXT,
        primary key (id)
    );

    create table patient (
        id bigint not null,
        prescriber_id bigint,
        primary key (id)
    );

    create table pittsburgh_scale (
        actual_sleep_hours float4,
        assessment_date date not null,
        freq_cannot_breathe integer,
        freq_cannot_fall_asleep integer,
        freq_cough_or_snore integer,
        freq_feel_cold integer,
        freq_feel_hot integer,
        freq_have_bad_dreams integer,
        freq_have_pain integer,
        freq_trouble_staying_awake integer,
        freq_use_sleep_medication integer,
        freq_wake_up_for_bathroom integer,
        freq_wakes_up_middle_night integer,
        minutes_to_fall_asleep integer,
        psqi_score integer,
        room_partner integer,
        sleep_quality_rating integer,
        trouble_with_enthusiasm integer,
        usual_bed_time time(6),
        usual_wake_up_time time(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        other_reason_to_trouble_sleep TEXT,
        primary key (id)
    );

    create table prescriber (
        id bigint not null,
        profession varchar(255),
        professional_code varchar(255) unique,
        registry_number varchar(255),
        registry_type varchar(255),
        primary key (id),
        unique (registry_type, registry_number)
    );

    create table prescription (
        appointment_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        brand varchar(255),
        concentration varchar(255),
        observation TEXT,
        posology TEXT,
        product_description TEXT,
        spectrum varchar(255),
        primary key (id)
    );

    create table sleep_log (
        alcohol_consumption integer,
        assessment_date date not null,
        bed_time time(6),
        coffee_consumption integer,
        daytime_sleepiness integer,
        fatigue integer,
        health_perception integer,
        inattention integer,
        irritability integer,
        is_common_day boolean,
        naps_time integer,
        nighttime_smoking integer,
        pain integer,
        physical_activity_time float4,
        stress integer,
        time_away_from_home float4,
        time_in_bed float4,
        time_to_fall_asleep integer,
        times_woken_up integer,
        total_awake_sleep float4,
        total_sleep_time float4,
        total_time_awake integer,
        total_time_awake_during_night integer,
        used_sleep_medication boolean,
        wake_up_time time(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table tealog (
        assessment_date date not null,
        freq_aggressiveness integer,
        freq_agitation integer,
        freq_appetite_issues integer,
        freq_sleep_issues integer,
        freq_social_interaction integer,
        freq_stereotypy integer,
        tea_score integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        observation TEXT,
        primary key (id)
    );

    create table users (
        birth_date date,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        city varchar(255),
        country varchar(255),
        cpf varchar(255) unique,
        email varchar(255) unique,
        name varchar(255),
        number varchar(255),
        password varchar(255),
        phone varchar(255),
        state varchar(255),
        street varchar(255),
        primary key (id)
    );

    alter table if exists anamnesis 
       add constraint FK61fa1ykng3jb6ywyjs4d4xh8o 
       foreign key (patient_id) 
       references patient;

    alter table if exists appointment 
       add constraint FK4apif2ewfyf14077ichee8g06 
       foreign key (patient_id) 
       references patient;

    alter table if exists appointment 
       add constraint FKd371rnve44fqmhufkbk4p7ge2 
       foreign key (prescriber_id) 
       references prescriber;

    alter table if exists assigned_scale 
       add constraint FK9gfktg8brg20hba0t77lrulk8 
       foreign key (patient_id) 
       references patient;

    alter table if exists assigned_scale 
       add constraint FKmjdofic74i6hgk06ibibgey78 
       foreign key (prescriber_id) 
       references prescriber;

    alter table if exists follow_up 
       add constraint FKftp457ksutfwdfjj8llol443o 
       foreign key (patient_id) 
       references patient;

    alter table if exists hamilton_scale 
       add constraint FKrahysmdvmxf7602chbdoig3em 
       foreign key (patient_id) 
       references patient;

    alter table if exists mental_state_exam 
       add constraint FK5b5p7ant1awa1xmlao7ror4kx 
       foreign key (appointment_id) 
       references appointment;

    alter table if exists notification 
       add constraint FKnk4ftb5am9ubmkv1661h15ds9 
       foreign key (user_id) 
       references users;

    alter table if exists pain_log 
       add constraint FK86jynehwumgv41lbny6m0f960 
       foreign key (patient_id) 
       references patient;

    alter table if exists patient 
       add constraint FKfv6f5wu9icyjkw4xl5wyi7sh0 
       foreign key (prescriber_id) 
       references prescriber;

    alter table if exists patient 
       add constraint FKf0or75ex3abs31ottuqg8s301 
       foreign key (id) 
       references users;

    alter table if exists pittsburgh_scale 
       add constraint FKsiurohwdskwhnqp6n5u82x64r 
       foreign key (patient_id) 
       references patient;

    alter table if exists prescriber 
       add constraint FK18h84avr5w3qwhvtnnwaa4qef 
       foreign key (id) 
       references users;

    alter table if exists prescription 
       add constraint FKba3shvghb1nrydjy9khc9c6a7 
       foreign key (appointment_id) 
       references appointment;

    alter table if exists sleep_log 
       add constraint FKquhoj5y6a4urfnjowlel132m8 
       foreign key (patient_id) 
       references patient;

    alter table if exists tealog 
       add constraint FKreoom038e5o30p8dw41ihp9js 
       foreign key (patient_id) 
       references patient;
