-- convite q o prescritor gera pro paciente se cadastrar ja vinculado a ele (RN06)
-- o link leva um codigo aleatorio e o banco guarda so o hash desse codigo
-- cada convite serve pra um cadastro e vence em poucos dias

create table patient_invite (
    id bigint generated by default as identity,
    prescriber_id bigint not null,
    token_hash varchar(64) not null unique,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    used_at timestamp(6),
    patient_id bigint,
    primary key (id),
    constraint fk_patient_invite_prescriber foreign key (prescriber_id) references prescriber (id),
    constraint fk_patient_invite_patient foreign key (patient_id) references patient (id)
);

create index idx_patient_invite_prescriber on patient_invite (prescriber_id);
create index idx_patient_invite_patient on patient_invite (patient_id);
