-- a conduta da clinica eh comecar com dose baixa e subir devagar, entao
-- a prescricao n tem uma dose so: tem um plano semana a semana.
-- a tela ja coletava esse plano e ele se perdia no caminho.
--
-- guardar em tabela propria, e n como texto, eh o que vai permitir
-- montar o historico de ajuste de dose que a prescritora pediu.

alter table prescription add column volume varchar(255);
alter table prescription add column administration_route varchar(255);
alter table prescription add column instructions TEXT;
alter table prescription add column precautions TEXT;
alter table prescription add column expected_effects TEXT;
alter table prescription add column treatment_duration_days integer;
alter table prescription add column next_consultation_date date;

create table dose_escalation_step (
    id bigint generated by default as identity,
    week integer,
    dosage varchar(255),
    note TEXT,
    prescription_id bigint not null,
    primary key (id)
);

alter table dose_escalation_step
    add constraint fk_dose_escalation_step_prescription
    foreign key (prescription_id) references prescription;
