-- aceite do termo de consentimento no cadastro (RF36 e LGPD art. 11)
-- cada aceite guarda a versao do termo e o momento em q foi aceito
-- quando o termo mudar o aceite novo entra do lado do antigo e o historico fica

create table consent_acceptance (
    id bigint generated by default as identity,
    user_id bigint not null,
    term_version varchar(40) not null,
    accepted_at timestamp(6) not null,
    primary key (id),
    constraint fk_consent_acceptance_users foreign key (user_id) references users (id)
);

create index idx_consent_acceptance_user on consent_acceptance (user_id);
