-- pedido de recuperacao de senha por e-mail (RF35)
-- o link leva um codigo aleatorio e o banco guarda so o hash dele
-- cada link serve uma vez e vence em 30 minutos

create table password_reset (
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(64) not null unique,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    used_at timestamp(6),
    primary key (id),
    constraint fk_password_reset_users foreign key (user_id) references users (id)
);

create index idx_password_reset_user on password_reset (user_id, created_at);
