-- o protocolo eh o que faz o sistema designar as escalas sozinho ao
-- longo dos 90 dias, em vez de a prescritora ter que mandar uma por uma
-- pra cada paciente.
--
-- era a sobrecarga relatada na entrevista de 2025: ela acumula a parte
-- clinica e a administrativa, sozinha.

create table treatment_protocol (
    id bigint generated by default as identity,
    patient_id bigint not null,
    prescriber_id bigint not null,
    start_date date not null,
    end_date date not null,
    active boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table protocol_item (
    id bigint generated by default as identity,
    scale_type varchar(255) not null,
    periodicity varchar(255) not null,
    protocol_id bigint not null,
    primary key (id)
);

alter table treatment_protocol
    add constraint fk_treatment_protocol_patient
    foreign key (patient_id) references patient;

alter table treatment_protocol
    add constraint fk_treatment_protocol_prescriber
    foreign key (prescriber_id) references prescriber;

alter table protocol_item
    add constraint fk_protocol_item_protocol
    foreign key (protocol_id) references treatment_protocol;
