-- trilha de auditoria do prontuario (RF31)
-- a tabela so recebe insercao e a api n tem rota pra alterar nem pra apagar evento
-- actor_id nulo quer dizer q quem fez foi o proprio sistema como o acompanhamento automatico
-- patient_id eh o dono do registro e serve pra consultar a trilha por paciente

create table audit_event (
    id bigint generated by default as identity,
    occurred_at timestamp(6) not null,
    actor_id bigint,
    actor_role varchar(20) check (actor_role in ('PATIENT', 'PRESCRIBER', 'ADMIN')),
    operation varchar(20) not null check (operation in ('CRIACAO', 'ALTERACAO', 'VISUALIZACAO')),
    record_type varchar(40) not null check (record_type in ('PRONTUARIO', 'CONSULTA', 'PRESCRICAO', 'MINI_EXAME',
        'ANAMNESE', 'ACOMPANHAMENTO_SEMANAL', 'ESCALA_HAMILTON', 'ESCALA_PITTSBURGH', 'REGISTRO_DOR',
        'REGISTRO_SONO', 'REGISTRO_TEA', 'DESIGNACAO_DE_ESCALA', 'ACOMPANHAMENTO_AUTOMATICO')),
    record_id bigint,
    patient_id bigint not null,
    primary key (id),
    constraint fk_audit_event_actor foreign key (actor_id) references users (id),
    constraint fk_audit_event_patient foreign key (patient_id) references patient (id)
);

create index idx_audit_event_patient on audit_event (patient_id, occurred_at);
create index idx_audit_event_occurred on audit_event (occurred_at);
create index idx_audit_event_actor on audit_event (actor_id, patient_id, occurred_at);
