-- prescricao vigente e composicao do oleo (RF05)
-- a prescricao nova substitui a vigente e a anterior fica no historico como substituida
-- o oleo vira uma lista de canabinoides cada um com a propria concentracao ate a clinica responder a pergunta 1
-- prescricao errada eh anulada com motivo e continua no historico

alter table prescription add column status varchar(20) default 'VIGENTE' not null;
alter table prescription add constraint ck_prescription_status check (status in ('VIGENTE', 'SUBSTITUIDA'));
alter table prescription add constraint ck_prescription_spectrum
    check (spectrum in ('ISOLADO', 'BROAD_SPECTRUM', 'FULL_SPECTRUM'));
alter table prescription add column batch varchar(255);
alter table prescription drop column concentration;

alter table prescription add column annulled_at timestamp(6);
alter table prescription add column annulled_by_id bigint;
alter table prescription add column annulment_reason TEXT;
alter table prescription add constraint fk_prescription_annulled_by foreign key (annulled_by_id) references users (id);

create table prescription_component (
    id bigint generated by default as identity,
    prescription_id bigint not null,
    cannabinoid varchar(20) not null,
    concentration numeric(10, 3) not null,
    unit varchar(20) not null,
    primary key (id),
    constraint ck_prescription_component_cannabinoid
        check (cannabinoid in ('CBD', 'THC', 'CBG', 'CBN', 'CBC', 'THCV', 'CBDA', 'OUTRO')),
    constraint ck_prescription_component_unit check (unit in ('PERCENTUAL', 'MG_POR_ML')),
    constraint fk_prescription_component_prescription foreign key (prescription_id) references prescription (id)
);

create index idx_prescription_component_prescription on prescription_component (prescription_id);
